### PR TITLE
Harden the API

### LINKED ISSUE #14: Harden the SILO api
Make the SILO API more resistant to errors:
- /query should only accept POST requests.
- /info should only accept GET requests.
- Make sure that there is proper error handling in place: i.e. if an exception is thrown, the application doesn't terminate, but responds with an appropriate HTTP repsonse.
- The response should always be a valid JSON in a defined format.

### PR DESCRIPTION
**Pull request by fengelniederhammer**
resolves #14

### CODE REVIEW

File: include/silo_api/info_handler.h [hunk 1]
```diff
@@ -1,26 +1,25 @@
 #ifndef SILO_INFOHANDLER_H
 #define SILO_INFOHANDLER_H
 
-#include <Poco/Net/HTTPRequestHandler.h>
 #include <Poco/Net/HTTPServerRequest.h>
 #include <Poco/Net/HTTPServerResponse.h>
 
+#include "silo_api/request_handler.h"
```
Comment (JonasKellerer) [inline include/silo_api/info_handler.h:7]: We could make this a forward declaration `class RestResource;`. This makes the build faster, and it is clearer, where `RestResource` comes from.

File: src/silo_api/request_handler.test.cpp [hunk 2]
```diff
@@ -0,0 +1,74 @@
...
+  public:
+   MOCK_METHOD(
+      void,
+      handleRequest,
+      (Poco::Net::HTTPServerRequest & request, Poco::Net::HTTPServerResponse& response),
+      ()
+   );
+};
+
+TEST(ErrorRequestHandler, handlesRuntimeErrors) {
```
Comment (JonasKellerer) [inline src/silo_api/request_handler.test.cpp:17]: In other test cases we used snake case. Which do we prefer? Google says, that CamelCase would be better, because of strange leading underscore stuff. We should add this to the README

File: src/silo_api/request_handler.test.cpp [hunk 3]
```diff
@@ -0,0 +1,74 @@
...
+   auto under_test = silo_api::ErrorRequestHandler(wrapped_handler_mock);
+
+   ON_CALL(*wrapped_handler_mock, handleRequest)
+      .WillByDefault(testing::Throw(std::runtime_error("my error message")));
+
+   silo_api::test::MockResponse response;
+   silo_api::test::MockRequest request(response);
+   under_test.handleRequest(request, response);
+
+   EXPECT_EQ(response.getStatus(), 500);
```
Comment (JonasKellerer) [inline src/silo_api/request_handler.test.cpp:29]: Maybe we could use [pocos responses](https://docs.pocoproject.org/current/Poco.Net.HTTPResponse.html)?

File: src/silo_api/request_handler.test.cpp (hunk 2 above)
Comment (fengelniederhammer) [reply src/silo_api/request_handler.test.cpp:17]: The docs say that one should not use `_` in test names: https://github.com/google/googletest/blob/main/docs/faq.md#why-should-test-suite-names-and-test-names-not-contain-underscore

File: include/silo_api/info_handler.h (hunk 1 above)
Comment (fengelniederhammer) [reply include/silo_api/info_handler.h:7]: I didn't manage to make it work since `InfoHandler` inherits from `RestResource`, i.e. The this header file needs to know about the structure of `RestResource`.

File: include/silo_api/request_handler.h [hunk 4]
```diff
@@ -6,8 +6,17 @@
...
+#include <nlohmann/json.hpp>
 
 namespace silo_api {
+
+struct ErrorResponse {
+   std::string error;
+   std::string message;
+};
+
+NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(ErrorResponse, error, message);
```
[the remark this answers is not in the document]
Comment (fengelniederhammer) [reply include/silo_api/request_handler.h:18]: Doesn't work, because the `InfoHandler` needs to know that the generated functions exist. The alternative would be to only declare the functions here and include the macro in the .cpp file, but that results in more code...

[the remark this answers is not in the document]
Comment (JonasKellerer) [reply include/silo_api/request_handler.h:18]: If there will be more, we can consider doing this. For now I would suggest leaving it like this.

File: src/silo_api/request_handler.test.cpp (hunk 2 above)
Comment (JonasKellerer) [reply src/silo_api/request_handler.test.cpp:17]: I'll have a look how to disable the clang-tidy functionality for this. Then I will change the test names accordingly. Maybe in a separate pull request.

File: include/silo_api/info_handler.h (hunk 1 above)
Comment (JonasKellerer) [reply include/silo_api/info_handler.h]: Sadly, me neither... 
I've pushed a commit, where each handler is put in its own file. Thus, `RestResource` can be found more easily. We can also think about putting the request handlers in their own folder. What do you think?

Comment (fengelniederhammer) [reply include/silo_api/info_handler.h]: Sounds reasonable, but for now IMO the `/silo_api` is already the separate folder. If the api layer grows further, we can still split it.

**Review by JonasKellerer — APPROVED** [review]
