### PR TITLE
fix: throw exceptions instead of terminating the program via the assert macro

### LINKED ISSUE #15: Make sure that failed `assert`s don't terminate the API
Currently the code contains a lot of `assert`s. Those terminate the API upon failure. E.g. reproduce with 

```
docker run -p 8080:8080 silo
curl --request POST --data '{
      "action": {
        "type": "Aggregated"
      },
      "filter": {}
    }' http://localhost:8080/query
```
yields "Assertion failed: js.HasMember("type") (/src/src/query_engine/query_engine.cpp: to_ex: 17)" and the API stops.

-> Make `assert` not terminate or throw exceptions instead.

### PR DESCRIPTION
**Pull request by fengelniederhammer**
resolves #15

Appreciate early feedback. I propose to solve this via a custom macro in which we can provide a custom error message. Using a macro has the advantage over a function, that we don't need to allocate the error message string if the check does not fail.

### CODE REVIEW

File: src/silo/query_engine/query_engine.cpp [hunk 1]
```diff
@@ -26,6 +26,11 @@
 #include "silo/database.h"
 #include "silo/query_engine/query_result.h"
 
+#define CHECK_SILO_QUERY(condition, message)    \
```
Comment (JonasKellerer) [inline src/silo/query_engine/query_engine.cpp:29]: Do we want to extend the macro, that it can also work with other exceptions (namely extending it with one more argument), or do we want to keep it specific to silo queries?

**Comment by JonasKellerer** [comment]
I like it. :) Makes it also easy to switch out, if we want to change it.

**Review by fengelniederhammer — COMMENTED** [review]
Looks good to me (can't approve it myself).

**Review by JonasKellerer — APPROVED** [review]
