### PR TITLE
fix: use arrow::acero::SourceNode when constructing a TableScan

### LINKED ISSUE #862: SILO cannot stream large sets of sequences
When attempting to request all sequences from SILO 0.7.1, it cannot stream the sequences but times out instead.

### PR DESCRIPTION
**Pull request by Taepper**
resolves #862

### Summary

The problem was that the `StartProducing` method was blocking. This means that while the results were already streamed through the execution plan (which is what I validated manually), the actual http response only started sending after `TableScan::StartProducing` terminated (see `src/silo/query_engine/query_plan.cpp:29` for the precise blocking line).

This means that memory consumption skyrocketed when requesting a large number of sequences. (Up until 1-2 million this was still not too noticable)

This fix makes use of a custom generator object in a generic `SinkNode` instead of rolling our own `TableScan` exec node. This is preferrable, as we do not need to concern ourselves with the following two details:
- Backpressure forwarding: The generic sink node already has backpressure forwarding implemented. Therefore, the SourceNode will stop producing batches, when they are not consumed fast enough downstream
- Async execution: Our generator will be called asynchronously by the generic node

The arrow::acero::SourceNode reslices batches if they are bigger than 32768. We want to avoid this and therefore change the default batch size to this value for now. While it is possible to pass more config options to the arrow nodes, this should be done in a separate commit

## PR Checklist

~~- [ ] All necessary documentation has been adapted or there is an issue to do so.~~
~~- [ ] The implemented feature is covered by an appropriate test.~~

### CODE REVIEW

**Comment by Taepper** [comment]
This already fixes the mentioned contentions:

This is (part of) the log for downloading 80 GB data:
```
[2025-07-07 15:55:04.510] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 32238524 KB
[2025-07-07 15:55:09.511] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 32238524 KB
[2025-07-07 15:55:14.510] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 32238524 KB
[2025-07-07 15:55:19.510] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 32238524 KB
[2025-07-07 15:55:20.830] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:55:23.555] [logger] [trace] [query_plan.cpp:30] Plan started producing, will now read the resulting batches.
[2025-07-07 15:55:23.555] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:55:23.556] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:55:24.511] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 36587144 KB
[2025-07-07 15:55:26.563] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:55:27.351] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:55:29.510] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 38547788 KB
[2025-07-07 15:55:29.592] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:55:34.510] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 35322340 KB
[2025-07-07 15:55:35.159] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:55:39.510] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 34365860 KB
[2025-07-07 15:55:40.973] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:55:42.616] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:55:42.616] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:55:44.510] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 38597560 KB
[2025-07-07 15:55:45.621] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:55:48.839] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:55:49.510] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 37609200 KB
[2025-07-07 15:55:54.511] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 35336176 KB
[2025-07-07 15:55:54.903] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:55:59.511] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 34377712 KB
[2025-07-07 15:56:01.041] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:56:02.706] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:56:02.706] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:56:04.356] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:56:04.511] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 39822556 KB
[2025-07-07 15:56:08.972] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:56:09.510] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 37605512 KB
[2025-07-07 15:56:14.510] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 35332492 KB
[2025-07-07 15:56:15.050] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:56:19.510] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 34376076 KB
[2025-07-07 15:56:21.135] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:56:22.792] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:56:22.792] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:56:24.480] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:56:24.511] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 39107712 KB
[2025-07-07 15:56:28.966] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:56:29.510] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 37605508 KB
[2025-07-07 15:56:34.510] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 35332492 KB
[2025-07-07 15:56:35.086] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:56:39.510] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 34376076 KB
[2025-07-07 15:56:41.154] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:56:42.812] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:56:42.812] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:56:44.468] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:56:44.510] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 39077004 KB
[2025-07-07 15:56:49.030] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:56:49.511] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 37605548 KB
[2025-07-07 15:56:54.511] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 35332500 KB
[2025-07-07 15:56:55.159] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:56:59.511] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 34376084 KB
[2025-07-07 15:57:01.238] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:57:02.900] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:57:02.900] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:57:04.510] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 39214172 KB
[2025-07-07 15:57:04.683] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:57:09.141] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:57:09.511] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 37605528 KB
[2025-07-07 15:57:14.510] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 35332516 KB
[2025-07-07 15:57:15.250] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:57:19.511] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 34376100 KB
[2025-07-07 15:57:21.334] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:57:22.984] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:57:22.984] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:57:24.511] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 39216340 KB
[2025-07-07 15:57:24.764] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:57:29.197] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:57:29.510] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 37609628 KB
[2025-07-07 15:57:34.510] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 35336628 KB
[2025-07-07 15:57:35.309] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:57:39.510] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 34378164 KB
STOP[2025-07-07 15:57:41.313] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:57:42.977] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:57:42.977] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:57:44.511] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 39214740 KB
[2025-07-07 15:57:44.754] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:57:45.856] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:57:48.581] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:57:49.511] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 36649572 KB
[2025-07-07 15:57:51.309] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:57:52.973] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:57:52.973] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:57:54.510] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 39214972 KB
[2025-07-07 15:57:54.726] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:57:55.846] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:57:58.557] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:57:59.510] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 36649956 KB
[2025-07-07 15:58:01.261] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:58:02.954] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:58:02.954] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:58:04.510] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 39215100 KB
[2025-07-07 15:58:04.715] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:58:05.803] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:58:08.504] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:58:09.510] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 36649960 KB
[2025-07-07 15:58:11.203] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:58:12.874] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:58:12.874] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:58:14.510] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 39214888 KB
[2025-07-07 15:58:14.675] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:58:15.721] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:58:18.419] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:58:19.510] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 36649924 KB
[2025-07-07 15:58:21.114] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:58:22.776] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:58:22.776] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:58:24.454] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:58:24.511] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 39175760 KB
[2025-07-07 15:58:25.623] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:58:28.321] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:58:29.510] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 36655664 KB
[2025-07-07 15:58:31.025] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:58:32.687] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:58:32.687] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:58:34.337] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:58:34.511] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 39560872 KB
[2025-07-07 15:58:35.552] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:58:38.268] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:58:39.511] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 36655712 KB
[2025-07-07 15:58:40.959] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:58:42.613] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:58:42.613] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:58:44.278] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:58:44.511] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 40056500 KB
[2025-07-07 15:58:45.488] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:58:48.228] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:58:49.510] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 36659748 KB
[2025-07-07 15:58:50.945] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:58:52.609] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:58:52.609] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:58:54.259] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:58:54.510] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 40070824 KB
[2025-07-07 15:58:55.457] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:58:58.171] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:58:59.510] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 36655640 KB
[2025-07-07 15:59:00.878] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:59:02.542] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:59:02.542] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:59:04.190] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:59:04.510] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 40117948 KB
[2025-07-07 15:59:05.400] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:59:08.107] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:59:09.510] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 36655652 KB
[2025-07-07 15:59:10.810] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:59:12.478] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:59:12.478] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:59:14.122] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:59:14.510] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 40169136 KB
[2025-07-07 15:59:15.323] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:59:18.049] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:59:19.510] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 36655636 KB
[2025-07-07 15:59:20.752] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:59:22.412] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:59:22.413] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:59:24.065] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:59:24.510] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 40177352 KB
[2025-07-07 15:59:25.255] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:59:27.949] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:59:29.510] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 36356720 KB
[2025-07-07 15:59:30.646] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:59:32.312] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:59:32.312] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:59:33.982] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:59:34.511] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 40177344 KB
[2025-07-07 15:59:35.184] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:59:37.883] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:59:39.511] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 35854500 KB
[2025-07-07 15:59:40.580] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:59:42.253] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:59:42.253] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:59:43.907] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:59:44.511] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 40175416 KB
[2025-07-07 15:59:45.103] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:59:47.795] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:59:49.511] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 35470620 KB
[2025-07-07 15:59:50.496] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:59:52.180] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:59:52.180] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()
[2025-07-07 15:59:54.510] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 37972240 KB
[2025-07-07 15:59:55.027] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:59:55.122] [logger] [trace] [query_plan.cpp:33] await the next batch
[2025-07-07 15:59:55.122] [logger] [trace] [query_plan.cpp:47] Finished reading all batches.
[2025-07-07 15:59:59.510] [logger] [info] [memory_monitor.cpp:72] Current memory consumption: 32469832 KB
```

**Comment by Taepper** [comment]
However, it is still a problem, that the response does not end early when the network stream is interrupted. Note that I stopped the reading stream at:

`STOP[2025-07-07 15:57:41.313] [logger] [trace] [table_scan.h:75] TableScanGenerator::operator()`

File: src/silo/query_engine/exec_node/ndjson_sink.cpp [hunk 1]
```diff
@@ -92,7 +98,9 @@ arrow::Status createGenerator(
    arrow::acero::ExecNode* input,
```
Comment (anna-parker) [inline src/silo/query_engine/exec_node/ndjson_sink.cpp:98]: The arrow docs warn that https://arrow.apache.org/docs/cpp/acero/overview.html#execplan, 
"ExecPlan is an internal concept. Users creating plans should be using Declaration objects. APIs for consuming and executing plans should abstract away the details of the underlying plan and not expose the object itself."

But I see we are creating an ExecPlan and passing it to `QueryPlan::makeQueryPlan` is this a problem?

File: src/silo/query_engine/exec_node/table_scan.h
Comment (anna-parker) [inline src/silo/query_engine/exec_node/table_scan.h:1]: should the name of this file be changed as the class is no longer called `TableScan` but `ExecBatchBuilder`?

Comment (Taepper) [reply src/silo/query_engine/exec_node/table_scan.h:1]: There is still the function `makeTableScan` at the bottom.

Furthermore it consists of the two related classes `TableScanGenerator` and `ExecBatchBuilder`

File: src/silo/query_engine/query_plan.cpp [hunk 2]
```diff
@@ -66,11 +66,15 @@ arrow::Status QueryPlan::executeAndWriteImpl(std::ostream* output_stream) {
 void QueryPlan::executeAndWrite(std::ostream* output_stream) {
    auto status = executeAndWriteImpl(output_stream);
    if (!status.ok()) {
-      throw std::runtime_error(fmt::format(
-         "Internal server error. Please notify developers. SILO constructed an invalid arrow plan. "
-         "It is likely that more user-input validation needs to be added: {}",
-         status.ToString()
-      ));
+      if (status.IsIOError()) {
+         SPDLOG_ERROR("The request {} encountered an IO Error when sending the response");
```
Comment (anna-parker) [inline src/silo/query_engine/query_plan.cpp:70]: shouldn't this throw an error?

File: src/silo/config/runtime_config.cpp [hunk 3]
```diff
@@ -103,7 +103,7 @@ ConfigSpecification RuntimeConfig::getConfigSpecification() {
             ),
             ConfigAttributeSpecification::createWithDefault(
                queryMaterializationOptionKey(),
-               ConfigValue::fromUint32(50000),
+               ConfigValue::fromUint32(32767),
```
[the remark this answers is not in the document]
Comment (fengelniederhammer) [reply src/silo/config/runtime_config.cpp:106]: It would prefer no extract it to a constant that tells the purpose by its name. There the information is hardest to lose.

**Review by fengelniederhammer — APPROVED** [review]
I didn't test it at larger scale, but it look reasonable to me

**Comment by Taepper** [comment]
> Would it be possible to add an Integration/End-to-End Test that verifies the streaming start doesn't get blocked?

Good idea. I think this would require quite some infrastructure around the actual test code, which is not feasible as of now. I added the log to this PR to show that it is actually streaming the batches, but I do not currently have any plan on extending our testing infrastructure
